# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:02:11+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class DateRange(BaseModel):
    from_: str = Field(
        ...,
        alias='from',
        description='Indicates the date and time when the fixed price will start to be valid.',
    )
    to: str = Field(
        ...,
        description='Indicates the date and time from which the fixed price will no longer be valid.',
    )


class FixedPrice(BaseModel):
    dateRange: Optional[DateRange] = None
    listPrice: float = Field(..., description='Trade Policy List Price Value.')
    minQuantity: int = Field(
        ..., description='Trade Policy Fixed Price Minimum Item Quantity.'
    )
    tradePolicyId: str = Field(..., description='Trade Policy ID.')
    value: float = Field(..., description='Trade Policy Fixed Price Value.')


class Getcomputedprice(BaseModel):
    costPrice: Optional[float] = Field(None, description='Cost price.')
    listPrice: int = Field(
        ..., description='Trade Policy List Price, also known as "from" price.'
    )
    priceValidUntil: str = Field(
        ...,
        description='Date until when the computed price will be valid, due to price scheduling. If no price scheduling applies, this will be set a year from the current time.',
    )
    sellingPrice: float = Field(
        ...,
        description='Computed Price before applying coupons, promotions and taxes. This price may change before reaching the shelf.',
    )
    tradePolicyId: str = Field(..., description='Trade Policy ID.')


class Getprice(BaseModel):
    basePrice: int = Field(..., description="SKU's reference price.")
    costPrice: int = Field(..., description="SKU's cost price.")
    fixedPrices: List[FixedPrice] = Field(
        ...,
        description='The fixed price is a price that overlaps all other existing price configurations of a price table.',
    )
    itemId: str = Field(..., description='SKU ID.')
    listPrice: int = Field(..., description='Suggested retail price for the SKU.')
    markup: int = Field(..., description="Desired profit margin with the SKU's sale.")


class PriceVariation(BaseModel):
    lowerLimit: Optional[int] = Field(
        None, description='Lower variation limit.', examples=[1]
    )
    upperLimit: Optional[int] = Field(
        None, description='Upper variation limit.', examples=[10]
    )


class TradePolicyConfig(BaseModel):
    minimumMarkup: Optional[int] = Field(
        None, description='Trade Policy Minimum Markup.', examples=[80]
    )
    rulesShouldAffectListPrice: Optional[bool] = Field(
        None,
        description='Defines if the Price Rule should affect the list price too.',
        examples=[False],
    )
    tradePolicyId: Optional[str] = Field(
        None, description='Trade Policy ID.', examples=['b2c']
    )


class PricingConfiguration(BaseModel):
    blockAccount: Optional[bool] = Field(
        None,
        description='Defines if access to the Pricing APIs is blocked for external requests.',
        examples=[False],
    )
    blockedRoutes: Optional[List[str]] = Field(
        None, description='Array with all blocked routes.'
    )
    defaultMarkup: int = Field(..., description='Account default markup.', examples=[2])
    hasMigrated: bool = Field(
        ...,
        description='Defines if the account has migrated to Pricing V2.',
        examples=[True],
    )
    hasOptionalBasePrice: Optional[bool] = Field(
        None, description='Defines if optional base price is allowed.', examples=[False]
    )
    hasPriceInheritance: Optional[bool] = Field(
        None, description='Deprecated. Use the `priceInheritance` field instead.'
    )
    migrationStatus: Optional[str] = Field(
        None, description='Pricing V2 migration status.', examples=['Completed']
    )
    minimumMarkups: Dict[str, int] = Field(..., description='Account minimum markup.')
    priceInheritance: Optional[str] = Field(
        None,
        description='Condition of price inheritance from its parent account. This field can have three possible values: `never` if the store should never inherit prices, `nonexistent` if the store should only inherit prices in case of nonexistent prices for a given product, or `always` if the store should always inherit prices, regardless of its own prices.',
        examples=['nonexistent'],
    )
    priceTableLimit: Optional[int] = Field(
        None, description='Price Table Limit.', examples=[100]
    )
    priceTableSelectionStrategy: Optional[str] = Field(
        'first',
        description='The strategy used to get prices when there is more than one option. Possible values: `first`, `highest`, `lowest`. Default: `first`.',
        examples=['highest'],
    )
    priceVariation: Optional[PriceVariation] = Field(
        None, description='Price Variation object.'
    )
    sellersToOverride: Optional[List] = Field(
        None, description='Overrides prices from sellers.'
    )
    tradePolicyConfigs: Optional[List[TradePolicyConfig]] = Field(
        None, description='Trade Policy Configurations array.'
    )


class PricingMigrationGetResponse(BaseModel):
    hasMigrated: Optional[bool] = Field(
        None,
        description='Defines if the account has migrated to Pricing V2.',
        examples=[True],
    )
    isActive: Optional[bool] = Field(
        None, description='Defines if the account is active.', examples=[True]
    )


class DateRange1(BaseModel):
    from_: Optional[str] = Field(
        None,
        alias='from',
        description='Date when rule will be activated. Date format: `RFC3339`.',
    )
    to: Optional[str] = Field(
        None,
        description='Date when the rule will be deactivated. Date format: `RFC3339`.',
    )


class MarkupRange(BaseModel):
    from_: Optional[int] = Field(
        None,
        alias='from',
        description='Item markup should be greater than or equal to this value.',
    )
    to: Optional[int] = Field(
        None, description='Item markup should be less than or equal to this value.'
    )


class Context(BaseModel):
    brands: Optional[Dict[str, str]] = Field(
        None,
        description='Brands that an item should have to be eligible for the rule. Format: key: `brandId`, value: `brandName`.',
    )
    categories: Optional[Dict[str, str]] = Field(
        None,
        description='Categories that an item should have to be eligible for the rule. Format: key: `categoryId`, value: `categoryName`.',
    )
    dateRange: Optional[DateRange1] = Field(
        None, description='The rule will be active during this time range.'
    )
    internalCategories: Optional[Dict[str, Any]] = Field(
        None, description='Internal Categories.'
    )
    markupRange: Optional[MarkupRange] = Field(
        None,
        description="For an item to be eligible to the rule, it's markup should be in this Markup Range.",
    )
    stockStatuses: Optional[Dict[str, Any]] = Field(None, description='Stock statuses.')


class Rule(BaseModel):
    context: Optional[Context] = Field(
        None,
        description='Rule Context is a group of filters to be checked at an item level when applying the rule. If all those filters check out, the rule will be applied for that item, unless there is a fixed price for that item.',
    )
    id: Optional[float] = Field(None, description='Rule ID.')


class PricingPipelineCatalogGetResponseItem(BaseModel):
    percentualModifier: Optional[int] = Field(None, description='Percentual modifier.')
    rules: Optional[List[Rule]] = Field(
        None, description='Array of rules for the price table.'
    )
    tradePolicyId: Optional[str] = Field(
        None, description='Trade Policy ID (Price Table ID).'
    )


class PricingPipelineCatalogGetResponse(
    RootModel[List[PricingPipelineCatalogGetResponseItem]]
):
    root: List[PricingPipelineCatalogGetResponseItem] = Field(..., title='')


class Context1(BaseModel):
    brands: Optional[Dict[str, str]] = Field(
        None,
        description='Brands that an item should have to be eligible for the rule. Format: key: `brandId`, value: `brandName`.',
    )
    categories: Optional[Dict[str, str]] = Field(
        None,
        description='Categories that an item should have to be eligible for the rule. Format: key: `categoryId`, value: `categoryName`.',
    )
    dateRange: Optional[DateRange1] = Field(
        None, description='The rule will be active during this time range.'
    )
    internalCategories: Optional[Dict[str, Any]] = Field(
        None, description='Internal Categories.'
    )
    markupRange: Optional[MarkupRange] = Field(
        None,
        description="For an item to be eligible to the rule, it's markup should be in this Markup Range.",
    )
    stockStatuses: Optional[Dict[str, Any]] = Field(None, description='Stock statuses.')


class Rule1(BaseModel):
    context: Optional[Context1] = Field(
        None,
        description='Rule Context is a group of filters to be checked at an item level when applying the rule. If all those filters check out, the rule will be applied for that item, unless there is a fixed price for that item.',
    )
    id: Optional[float] = Field(None, description='Rule ID.')


class PricingPipelineCatalogPriceTableIdGetResponse(BaseModel):
    percentualModifier: Optional[int] = Field(None, description='Percentual modifier.')
    rules: Optional[List[Rule1]] = Field(
        None, description='Array of rules for the price table.'
    )
    tradePolicyId: Optional[str] = Field(
        None, description='Trade Policy ID (Price Table ID).'
    )


class DateRange3(BaseModel):
    from_: str = Field(
        ...,
        alias='from',
        description='Date when rule will be activated. Date format: `RFC3339`.',
        examples=['2019-10-23T19:00:00.000Z'],
        title='from',
    )
    to: str = Field(
        ...,
        description='Date when the rule will be deactivated. Date format: `RFC3339`.',
        examples=['2019-10-26T00:00:00.000Z'],
        title='to',
    )


class MarkupRange2(BaseModel):
    from_: int = Field(
        ...,
        alias='from',
        description='Item markup should be greater than or equal to this value.',
        examples=[0],
        title='from',
    )
    to: int = Field(
        ...,
        description='Item markup should be less than or equal to this value.',
        examples=[200],
        title='to',
    )


class Context2(BaseModel):
    brands: Dict[str, str] = Field(
        ...,
        description='Brands that an item should have to be eligible for the rule. Format: key: `brandId`, value: `brandName`.',
        title='brands',
    )
    categories: Dict[str, str] = Field(
        ...,
        description='Categories that an item should have to be eligible for the rule. Format: key: `categoryId`, value: `categoryName`.',
        title='categories',
    )
    dateRange: DateRange3 = Field(
        ...,
        description='The rule will be active during this time range.',
        title='dateRange',
    )
    internalCategories: Optional[Dict[str, Any]] = Field(
        None,
        description='Internal Categories.',
        examples=[None],
        title='internalCategories',
    )
    markupRange: MarkupRange2 = Field(
        ...,
        description="For an item to be eligible to the rule, it's markup should be in this Markup Range.",
        examples=[None],
        title='markupRange',
    )
    stockStatuses: Optional[Dict[str, Any]] = Field(
        None, description='Stock statuses.', examples=[None], title='stockStatuses'
    )


class Rule2(BaseModel):
    context: Context2 = Field(
        ...,
        description='Rule Context is a group of filters to be checked at an item level when applying the rule. If all those filters check out, the rule will be applied for that item, unless there is a fixed price for that item.',
        title='context',
    )
    id: int = Field(..., description='Rule ID.', examples=[0], title='id')
    percentualModifier: float = Field(
        ...,
        description='Percentual modifier.',
        examples=[0],
        title='percentualModifier',
    )


class PricingPipelineCatalogPriceTableIdPutRequest(BaseModel):
    rules: List[Rule2] = Field(
        ..., description='Array of rules for the price table.', title='rules'
    )


class DateRange4(BaseModel):
    from_: str = Field(
        ...,
        alias='from',
        description='Start date of the price.',
        examples=['2021-12-30T22:00:00-03:00'],
        title='from',
    )
    to: str = Field(
        ...,
        description='End date of the price.',
        examples=['2021-12-30T22:00:00-03:00'],
        title='to',
    )


class FixedPrice1(BaseModel):
    dateRange: Optional[DateRange4] = Field(
        None,
        description='Period of time when the fixed price will be applied to the SKU.',
        title='dateRange',
    )
    listPrice: Optional[float] = Field(
        None, description='SKU List Fixed Price.', examples=[50.5], title='listPrice'
    )
    minQuantity: int = Field(
        ...,
        description='Minimum quantity of the SKU for the fixed price to be applied.',
        examples=[2],
        title='minQuantity',
    )
    tradePolicyId: str = Field(
        ...,
        description='Trade policy name or ID that will have the fixed price configured.',
        examples=['1'],
        title='tradePolicyId',
    )
    value: float = Field(
        ..., description='Fixed price value.', examples=[50.5], title='value'
    )


class PricingPricesItemIdPutRequest(BaseModel):
    basePrice: float = Field(
        ...,
        description='SKU selling base price. If you decide to fill only the `basePrice` item, the `markup` and `costPrice` will be automatically generated to adapt to the number inserted in `basePrice`.',
        title='basePrice',
    )
    costPrice: Optional[float] = Field(
        35,
        description='SKU selling cost price. If you decide to fill the `costPrice` item, you must also fill the `markup` and `basePrice` will be automatically generated based on both values.',
        title='costPrice',
    )
    fixedPrices: Optional[List[FixedPrice1]] = None
    listPrice: float = Field(
        ..., description="SKU's suggested selling price.", title='listPrice'
    )
    markup: int = Field(
        ...,
        description='The profit percentage that is to be obtained from the sale of that SKU. If you decide to fill the `markup` item, you must also fill the `costPrice`. The `basePrice` will be automatically generated based on both values.',
        title='markup',
    )


class PricingPricesItemIdFixedGetResponse(RootModel[List[FixedPrice]]):
    root: List[FixedPrice]


class PricingPricesItemIdFixedPriceTableIdGetResponse(RootModel[List[FixedPrice]]):
    root: List[FixedPrice]


class DateRange5(BaseModel):
    from_: str = Field(
        ...,
        alias='from',
        description='Start date of the price.',
        examples=['2021-12-30T22:00:00-03:00'],
        title='from',
    )
    to: str = Field(
        ...,
        description='End date of the price.',
        examples=['2021-12-30T22:00:00-04:00'],
        title='to',
    )


class PricingPricesItemIdFixedPriceTableIdPostRequestItem(BaseModel):
    dateRange: Optional[DateRange5] = Field(
        None,
        description='Period of time when the fixed price will be applied to the SKU.',
        title='dateRange',
    )
    listPrice: Optional[float] = Field(
        None, description='SKU List Fixed Price.', examples=[50.5], title='listPrice'
    )
    minQuantity: int = Field(
        ...,
        description='The minimum SKU quantity for the fixed price to be applied.',
        examples=[2],
        title='minQuantity',
    )
    value: float = Field(
        ..., description='Fixed price value.', examples=[50.5], title='value'
    )


class PricingPricesItemIdFixedPriceTableIdPostRequest(
    RootModel[List[PricingPricesItemIdFixedPriceTableIdPostRequestItem]]
):
    root: List[PricingPricesItemIdFixedPriceTableIdPostRequestItem] = Field(
        ..., title=''
    )


class PricingTablesGetResponse(RootModel[List[str]]):
    root: List[str] = Field(..., description='Array of price tables.')
